FROM postgres:16.4


COPY ./init.sql /docker-entrypoint-initdb.d/
COPY ./anime.sql /backup/anime.sql
COPY ./checklist.sql /backup/checklist.sql
COPY ./second-init-db.sh /docker-entrypoint-initdb.d/



EXPOSE 5432


