services:
  app:
    build: .
    container_name: vue-project
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:16.4
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: seanyew123

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./anime.sql:/backup/anime.sql
      - ./checklist.sql:/backup/checklist.sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

    ports:
      - "5432:5432"
    command: bash -c "docker-entrypoint.sh postgres"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: nuxt-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
