services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.vue-project
    container_name: vue-project
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres-db
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: seanyew123
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: nuxt-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
