# Sample workflow for building and deploying a Nuxt site to GitHub Pages
#
# To get started with Nuxt see: https://nuxtjs.org/docs/get-started/installation
#
name: Deploy Vue Project

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  # 1 job runs on 1 server
  # runs on parallel by default
  build:
    runs-on: ubuntu-latest
    # can choose macos, windows or linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the commit hash
        id: get_commit_hash
        run: |
          echo "TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: View commit hash
        run: echo ${{ env.TAG }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      # some tests to be performed here

      - name: Install dependencies
        run: npm install

      - name: Run nuxt build
        run: npm run build

  publish:
    needs: build
    runs-on:
      ubuntu-latest
      # can test on more than one OS with strategy, matrix and os
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login into docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: view env variable
        run: echo ${{ env.TAG }}
        
      - name: Build and push database
        uses: docker/build-push-action@v6
        with:
          context: ${{github.workspace}}
          file: ${{github.workspace}}/Dockerfile.postgres-db
          push: true
          tags: seanyew25/vue-project-db:${{ env.TAG }}

      - name: Build and push website
        uses: docker/build-push-action@v6
        with:
          context: ${{github.workspace}}
          file: ${{github.workspace}}/Dockerfile.vue-project
          push: true
          tags: seanyew25/vue-project-app:${{ env.TAG }}

  deploy:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: ssh into ec2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_RSA_KEY }}

      - name: stop existing containers and remove images
        run: |
          docker stop $(docker ps -q)
          docker rm $(docker ps -a -q)
          docker rmi $(docker images -q)

      - name: log into docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: pull images from docker
        run: |
          docker pull seanyew25/vue-project-db:${{ env.TAG }}
          docker pull seanyew25/vue-project-app:${{ env.TAG }}

      - name: docker compose
        run: docker compose up
